# Default policy configuration for MCP-Sec Gateway
rules:
  - name: "Default allow for trusted models"
    model: "*"
    allow_tools:
      - "search.*"
      - "calendar.*"
      - "email.read"
    
  - name: "Default deny for sensitive tools"
    model: "*"
    deny_tools:
      - "file.write"
      - "file.delete"
      - "system.*"
      - "execute.*"
      - "admin.*"
      - "config.*"