name: "Default Project Policy"
version: "1.0.0"
description: "Default policy for projects"
allow_models: ["gpt-4*", "claude*", "gemini*", "llama*"]
allow_tools: ["search.*", "file.read"]
deny_tools: ["system.*", "file.write"]
model_tool_map:
  "gpt-4*": ["search.*", "file.read"]
  "claude*": ["search.*"]
rate_limits:
  default:
    calls_per_minute: 10
    burst: 20
max_token_context: 4096